### ISSUE TITLE
Flaky test failure in FreeBSD CI

### ISSUE THREAD

**Issue by ifreund** [libcxxrt/libcxxrt#42]
Here's a sample from this CI run: https://github.com/libcxxrt/libcxxrt/runs/31481264193
```
2: Test command: /tmp/cirrus-ci-build/test/run_test.sh "/tmp/cirrus-ci-build/Build/bin/cxxrt-test-shared" "/tmp/cirrus-ci-build/Build/test/expected_output.log" "/tmp/cirrus-ci-build/Build/test/cxxrt-test-shared-output.log"
2: Working Directory: /tmp/cirrus-ci-build/Build/test
2: Test timeout computed to be: 10000000
2: 9c9
2: < 69 tests, 68 passed, 1 failed
2: ---
2: > 70 tests, 69 passed, 1 failed
2/4 Test #2: cxxrt-test-shared ................***Failed    1.01 sec
9c9
< 69 tests, 68 passed, 1 failed
---
> 70 tests, 69 passed, 1 failed
```
As far as I can tell, the "1 failed" here is referring to the following test which seems to be intended to fail?
```
Test failed: /root/libcxxrt/test/test_exception.cc:347: Caught int64_t, but that violates an exception spec
````

What actually seems to be causing the test suite as a whole to fail is the difference in the number of tests executed between the run testing libcxxrt and the run testing the system.

Looking through the tests, the most likely culprit seems to be the static initialization guard test:
https://github.com/libcxxrt/libcxxrt/blob/76435c4451aeb5e04e9500b090293347a38cef8d/test/test_guard.cc#L49-L54

I see also that there has been an attempt to fix this race already: https://github.com/libcxxrt/libcxxrt/pull/29/commits/75210453a0692bcab12e3b803c85c2ab92ffa9c4, it unfortunately seems that this was not sufficient.

**Comment by emaste** [comment]
CC @DimitryAndric

**Comment by davidchisnall** [comment]
Hmm, comment I posted yesterday did not appear:

The failing test is real, and is probably due to compiling as C++11.  With older C++, exception specifiers prevent exceptions from propagating and so we shouldn't see the uint64_t thrown.  In C++11 mode, we don't compile the exception specifier and so should disable this test.

The outer failure is because we are running a different number of tests against the system C++ runtime and the new libcxxrt.  We can probably disable that on FreeBSD, where the system runtime is just a different version of libcxxrt.  Comparing against libc++abi on macOS and libsupc++ on GNU/Linux is more useful.

**Comment by davidchisnall** [comment]
> As far as I can tell, the "1 failed" here is referring to the following test which seems to be intended to fail?

That is a slightly weird test.  Using 0 (false) as the condition is done because that code should be unreachable.  

I suspect that we're failing here because we're compiling the test in C++11 mode (or newer).  In C++11 mode, the exception specifier is compiled away (exception specs were deprecated and later removed in modern C++).  This means that the integer is caught, whereas it should trigger the unexpected exception handler.

The ctest test is failing because we're passing either one more or one fewer tests than the platform's default test.  We need to tweak the test runner configuration to make sure that we run the same number on both, or separate out the tests that may not work on the platform-native one to something that we don't run with the comparison.

Or we could probably just skip that comparison on FreeBSD (set `COMPARE_TEST_OUTPUT_TO_SYSTEM_OUTPUT` to `FALSE`), where the platform's native runtime is just a different version of libcxxrt.  These tests are mostly useful on macOS and GNU/Linux, where the platform's native runtimes are libsupc++ and libc++abi, respectively.

**Comment by davidchisnall** [comment]
Ah, there it is.
